(function(){var _util=CS.util,_uiBinder=CS.uiBinder,_mask=CS.mask,_dialog=CS.dialog;var _params={},_nodes={},_maskByModifyPwd=null,_isRequesting=0;var _ie6Tip='您当前的浏览器版本过低，部分功能无法正常使用，请及时升级';var _ie8Tip="您的浏览器版本太低，将不能正常使用作家专区。请升级 <a href='https://support.microsoft.com/zh-cn/help/17621' target=\"_blank\">Internet Explorer</a> 或使用 <a href='http://www.google.cn/chrome/browser/desktop/index.html' target=\"_blank\">Google Chrome</a> 浏览器。";var _ajaxUrls={'modifyPwd':'/Contentv2/Authors/authorPassUpdate.html','getMsgNotice':'/Contentv2/Authors/getNewMessageNote.html'};var _newMsgListTpl=['<cite class="icon"></cite>','<%each list as item index%>','<%if item.readstate == 0%>','<dd data-questionid="<%=item.IDX%>">','<span class="icon"></span><%=item.content%><a class="blue" href="<%=item.url%>">详情&gt;</a>','</dd>','<%/if%>','<%/each%>','<%if newMsgCount > 3%>','<dd data-node="more" class="more"><a href="/Authors/authorconsultlist.html">查看更多 &gt;</a></dd>','<%/if%>'].join('');function init(systemTip){_params.systemTip=systemTip||'';_nodes.$modifyPwdPopup=$('#modifyPwdPopup');updateMsgNotice();_setWarnTip();_setLoadingTip();_bindEvent();_leftMenuEffect();_adaptWindowSize();$(window).on('resize',function(){_util.throttle(_adaptWindowSize);});}
function _adaptWindowSize(){var windowWidth=$(window).width(),$leftNav=$('#leftNav');if(windowWidth<1000){$('html').addClass('w1000');}else{$('html').removeClass('w1000');}
if($leftNav.css('visibility')==='hidden'){$leftNav.css('visibility','visible');}}
function _leftMenuEffect(){$('#min-bar li').hover(function(){$(this).addClass('hover').find('.expand').fadeIn(100).css('right',-96);},function(){$(this).removeClass('hover').find('.expand').css('right',0).hide();});}
function updateMsgNotice(){if(_isRequesting){return;}
_isRequesting=1;_util.request({url:_ajaxUrls.getMsgNotice,type:'get',dataType:'json',data:{},isShowLoading:false,success:function(json){if(json&&json.status&&json.data){var $msgCount=$('#msgCount'),$msgList=$('#msgList');$msgCount.hide();$msgList.hide();if(json.data.newMessageNum>0){if(json.data.newMessageNum>99){$msgCount.text('99+').addClass('full');}else{$msgCount.text(json.data.newMessageNum).removeClass('full');}
$msgCount.show();if(json.data.list&&json.data.list.length>0){var tpl=_uiBinder.bindData(_newMsgListTpl,{'list':json.data.list,'newMsgCount':json.data.newMessageNum});$('#msgList').html(tpl).show();}}}},complete:function(){_isRequesting=0;}});}
function _setWarnTip(){if($.cookie('warntip')==='1'){return;}
var $box=$('#warnTipBox'),$tip=$('#warnTip');$('#warnTipCloseBtn').on('click',function(){$box.hide();$.cookie('warntip',1);return false;});if(!document.addEventListener){$tip.html(_ie8Tip);$box.show();}else if(_params.systemTip){$tip.html(_params.systemTip);$box.show();}}
function _setLoadingTip(){var $tip=$('#requestLoadingTip');if($tip.length>0){$('.mainRight').eq(0).append($tip);}}
function _bindEvent(){$('.hoverLi li').on('mouseover',function(){$(this).addClass('hover').siblings().removeClass('hover');});$(document.body).on('click','span.radio',function(){$(this).addClass('on').siblings('.radio').removeClass('on');$(this).find('input').attr('checked','checked').parent().siblings().find('input').removeAttr('checked');});$('#headPhotoBox').hover(function(){if(this.timer){clearTimeout(this.timer);}
$(this).find('dl').fadeIn();},function(){this.timer=setTimeout(function(){$('.userBox').stop().fadeOut(200);},200);});$('#openModifyPwdPopupBtn').on('click',function(){_openModifyPwdPopup();return false;});_nodes.$modifyPwdPopup.find('[data-node="closeBtn"]').on('click',function(){_closeModifyPwdPopup();return false;});_nodes.$modifyPwdPopup.find('[data-node="submitBtn"]').on('click',function(){if(_util.checkBtnIsLoading($(this))){return false;}
var originalPwd=_nodes.$modifyPwdPopup.find('[data-node="originalPwdInput"]').val(),newPwd=_nodes.$modifyPwdPopup.find('[data-node="newPwdInput"]').val(),repeatNewPwd=_nodes.$modifyPwdPopup.find('[data-node="repeatNewPwdInput"]').val();_modifyPwd($(this),originalPwd,newPwd,repeatNewPwd);return false;});_nodes.$modifyPwdPopup.find('[data-node="repeatNewPwdInput"]').on('keyup',function(event){if(event.keyCode===13){_nodes.$modifyPwdPopup.find('[data-node="submitBtn"]').trigger('click');}});}
function _modifyPwd($btn,originalPwd,newPwd,repeatNewPwd){if(!originalPwd||$.trim(originalPwd).length===0){_dialog.alert('请填写原始密码');return;}
if(!newPwd||$.trim(newPwd).length===0){_dialog.alert('请填写新密码');return;}
if(!repeatNewPwd||$.trim(repeatNewPwd).length===0){_dialog.alert('请再次输入新密码');return;}
if(newPwd!==repeatNewPwd){_dialog.alert('两次输入的新密码必须一致');return;}
if(_isRequesting){return;}
_isRequesting=1;_util.updateBtnText($btn,'loading');_util.request({url:_ajaxUrls.modifyPwd,type:'post',dataType:'json',data:{'old_password':originalPwd,'new_password':newPwd,'repeat_password':repeatNewPwd},success:function(json){if(!json){_dialog.alert('返回数据格式异常，请稍后再试');return;}
if(json.status){_closeModifyPwdPopup();_dialog.alert(json.info||'更改成功');}else{_dialog.alert(json.info||'操作失败，请稍后再试');}},error:function(){_dialog.alert('操作失败，请稍后再试');},complete:function(){_util.updateBtnText($btn,'default');_isRequesting=0;}});}
function _openModifyPwdPopup(){if(!_maskByModifyPwd){_maskByModifyPwd=new _mask(_nodes.$modifyPwdPopup);}
if(_maskByModifyPwd){_nodes.$modifyPwdPopup.find('input[type="password"]').val('');_maskByModifyPwd.open();}}
function _closeModifyPwdPopup(){if(_maskByModifyPwd){_maskByModifyPwd.close();}}
_util.initNameSpace("CS.page.layout");CS.page.layout.main={'init':init,'updateMsgNotice':updateMsgNotice};})(jQuery);